import ICurrencyOption from './ICurrencyOption';

export default <ICurrencyOption[]>[
  //   { name: 'Afghan Afghani', value: 'AFA' },
  //   { name: 'Albanian Lek', value: 'ALL' },
  //   { name: 'Algerian Dinar', value: 'DZD' },
  //   { name: 'Angolan Kwanza', value: 'AOA' },
  //   { name: 'Argentine Peso', value: 'ARS' },
  //   { name: 'Armenian Dram', value: 'AMD' },
  //   { name: 'Aruban Florin', value: 'AWG' },
  //   { name: 'Australian Dollar', value: 'AUD' },
  //   { name: 'Azerbaijani Manat', value: 'AZN' },
  //   { name: 'Bahamian Dollar', value: 'BSD' },
  //   { name: 'Bahraini Dinar', value: 'BHD' },
  //   { name: 'Bangladeshi Taka', value: 'BDT' },
  //   { name: 'Barbadian Dollar', value: 'BBD' },
  //   { name: 'Belarusian Ruble', value: 'BYR' },
  //   { name: 'Belgian Franc', value: 'BEF' },
  //   { name: 'Belize Dollar', value: 'BZD' },
  //   { name: 'Bermudan Dollar', value: 'BMD' },
  //   { name: 'Bhutanese Ngultrum', value: 'BTN' },
  //   { name: 'Bitcoin', value: 'BTC' },
  //   { name: 'Bolivian Boliviano', value: 'BOB' },
  //   { name: 'Bosnia-Herzegovina Convertible Mark', value: 'BAM' },
  //   { name: 'Botswanan Pula', value: 'BWP' },
  //   { name: 'Brazilian Real', value: 'BRL' },
  { name: 'british_pound', value: 'GBP', sign: '£' },
  //   { name: 'Brunei Dollar', value: 'BND' },/
  //   { name: 'Bulgarian Lev', value: 'BGN' },
  //   { name: 'Burundian Franc', value: 'BIF' },
  //   { name: 'Cambodian Riel', value: 'KHR' },
  //   { name: 'Canadian Dollar', value: 'CAD' },
  //   { name: 'Cape Verdean Escudo', value: 'CVE' },
  //   { name: 'Cayman Islands Dollar', value: 'KYD' },
  //   { name: 'CFA Franc BCEAO', value: 'XOF' },
  //   { name: 'CFA Franc BEAC', value: 'XAF' },
  //   { name: 'CFP Franc', value: 'XPF' },
  //   { name: 'Chilean Peso', value: 'CLP' },
  //   { name: 'Chilean Unit of Account', value: 'CLF' },
  //   { name: 'Chinese Yuan', value: 'CNY' },
  //   { name: 'Colombian Peso', value: 'COP' },
  //   { name: 'Comorian Franc', value: 'KMF' },
  //   { name: 'Congolese Franc', value: 'CDF' },
  //   { name: 'Costa Rican Colón', value: 'CRC' },
  //   { name: 'Croatian Kuna', value: 'HRK' },
  //   { name: 'Cuban Convertible Peso', value: 'CUC' },
  //   { name: 'Czech Republic Koruna', value: 'CZK' },
  //   { name: 'Danish Krone', value: 'DKK' },
  //   { name: 'Djiboutian Franc', value: 'DJF' },
  //   { name: 'Dominican Peso', value: 'DOP' },
  //   { name: 'East Caribbean Dollar', value: 'XCD' },
  //   { name: 'Egyptian Pound', value: 'EGP' },
  //   { name: 'Eritrean Nakfa', value: 'ERN' },
  //   { name: 'Estonian Kroon', value: 'EEK' },
  //   { name: 'Ethiopian Birr', value: 'ETB' },
  { name: 'euro', value: 'EUR', sign: '€' },
  //   { name: 'Falkland Islands Pound', value: 'FKP' },
  //   { name: 'Fijian Dollar', value: 'FJD' },
  //   { name: 'Gambian Dalasi', value: 'GMD' },
  //   { name: 'Georgian Lari', value: 'GEL' },
  //   { name: 'German Mark', value: 'DEM' },
  //   { name: 'Ghanaian Cedi', value: 'GHS' },
  //   { name: 'Gibraltar Pound', value: 'GIP' },
  //   { name: 'Greek Drachma', value: 'GRD' },
  //   { name: 'Guatemalan Quetzal', value: 'GTQ' },
  //   { name: 'Guinean Franc', value: 'GNF' },
  //   { name: 'Guyanaese Dollar', value: 'GYD' },
  //   { name: 'Haitian Gourde', value: 'HTG' },
  //   { name: 'Honduran Lempira', value: 'HNL' },
  //   { name: 'Hong Kong Dollar', value: 'HKD' },
  //   { name: 'Hungarian Forint', value: 'HUF' },
  //   { name: 'Icelandic Króna', value: 'ISK' },
  //   { name: 'Indian Rupee', value: 'INR' },
  //   { name: 'Indonesian Rupiah', value: 'IDR' },
  //   { name: 'Iranian Rial', value: 'IRR' },
  //   { name: 'Iraqi Dinar', value: 'IQD' },
  //   { name: 'Israeli New Sheqel', value: 'ILS' },
  //   { name: 'Italian Lira', value: 'ITL' },
  //   { name: 'Jamaican Dollar', value: 'JMD' },
  { name: 'japan_yen', value: 'JPY', sign: '¥' },
  //   { name: 'Jordanian Dinar', value: 'JOD' },
  //   { name: 'Kazakhstani Tenge', value: 'KZT' },
  //   { name: 'Kenyan Shilling', value: 'KES' },
  //   { name: 'Kuwaiti Dinar', value: 'KWD' },
  //   { name: 'Kyrgystani Som', value: 'KGS' },
  //   { name: 'Laotian Kip', value: 'LAK' },
  //   { name: 'Latvian Lats', value: 'LVL' },
  //   { name: 'Lebanese Pound', value: 'LBP' },
  //   { name: 'Lesotho Loti', value: 'LSL' },
  //   { name: 'Liberian Dollar', value: 'LRD' },
  //   { name: 'Libyan Dinar', value: 'LYD' },
  //   { name: 'Litecoin', value: 'LTC' },
  //   { name: 'Lithuanian Litas', value: 'LTL' },
  //   { name: 'Macanese Pataca', value: 'MOP' },
  //   { name: 'Macedonian Denar', value: 'MKD' },
  //   { name: 'Malagasy Ariary', value: 'MGA' },
  //   { name: 'Malawian Kwacha', value: 'MWK' },
  //   { name: 'Malaysian Ringgit', value: 'MYR' },
  //   { name: 'Maldivian Rufiyaa', value: 'MVR' },
  //   { name: 'Mauritanian Ouguiya', value: 'MRO' },
  //   { name: 'Mauritian Rupee', value: 'MUR' },
  //   { name: 'Mexican Peso', value: 'MXN' },
  //   { name: 'Moldovan Leu', value: 'MDL' },
  //   { name: 'Mongolian Tugrik', value: 'MNT' },
  //   { name: 'Moroccan Dirham', value: 'MAD' },
  //   { name: 'Mozambican Metical', value: 'MZM' },
  //   { name: 'Myanmar Kyat', value: 'MMK' },
  //   { name: 'Namibian Dollar', value: 'NAD' },
  //   { name: 'Nepalese Rupee', value: 'NPR' },
  //   { name: 'Netherlands Antillean Guilder', value: 'ANG' },
  //   { name: 'New Taiwan Dollar', value: 'TWD' },
  //   { name: 'New Zealand Dollar', value: 'NZD' },
  //   { name: 'Nicaraguan Córdoba', value: 'NIO' },
  //   { name: 'Nigerian Naira', value: 'NGN' },
  //   { name: 'North Korean Won', value: 'KPW' },
  //   { name: 'Norwegian Krone', value: 'NOK' },
  //   { name: 'Omani Rial', value: 'OMR' },
  //   { name: 'Pakistani Rupee', value: 'PKR' },
  //   { name: 'Panamanian Balboa', value: 'PAB' },
  //   { name: 'Papua New Guinean Kina', value: 'PGK' },
  //   { name: 'Paraguayan Guarani', value: 'PYG' },
  //   { name: 'Peruvian Nuevo Sol', value: 'PEN' },
  //   { name: 'Philippine Peso', value: 'PHP' },
  { name: 'polish_zloty', value: 'PLN', sign: 'zł' },
  //   { name: 'Qatari Rial', value: 'QAR' },
  //   { name: 'Romanian Leu', value: 'RON' },
  //   { name: 'Russian Ruble', value: 'RUB' },
  //   { name: 'Rwandan Franc', value: 'RWF' },
  //   { name: 'Salvadoran Colón', value: 'SVC' },
  //   { name: 'Samoan Tala', value: 'WST' },
  //   { name: 'São Tomé and Príncipe Dobra', value: 'STD' },
  //   { name: 'Saudi Riyal', value: 'SAR' },
  //   { name: 'Serbian Dinar', value: 'RSD' },
  //   { name: 'Seychellois Rupee', value: 'SCR' },
  //   { name: 'Sierra Leonean Leone', value: 'SLL' },
  //   { name: 'Singapore Dollar', value: 'SGD' },
  //   { name: 'Slovak Koruna', value: 'SKK' },
  //   { name: 'Solomon Islands Dollar', value: 'SBD' },
  //   { name: 'Somali Shilling', value: 'SOS' },
  //   { name: 'South African Rand', value: 'ZAR' },
  //   { name: 'South Korean Won', value: 'KRW' },
  //   { name: 'South Sudanese Pound', value: 'SSP' },
  //   { name: 'Special Drawing Rights', value: 'XDR' },
  //   { name: 'Sri Lankan Rupee', value: 'LKR' },
  //   { name: 'St. Helena Pound', value: 'SHP' },
  //   { name: 'Sudanese Pound', value: 'SDG' },
  //   { name: 'Surinamese Dollar', value: 'SRD' },
  //   { name: 'Swazi Lilangeni', value: 'SZL' },
  //   { name: 'Swedish Krona', value: 'SEK' },
  { name: 'swiss_franc', value: 'CHF', sign: '₣' },
  //   { name: 'Syrian Pound', value: 'SYP' },
  //   { name: 'Tajikistani Somoni', value: 'TJS' },
  //   { name: 'Tanzanian Shilling', value: 'TZS' },
  //   { name: 'Thai Baht', value: 'THB' },
  //   { name: "Tongan Pa'anga", value: 'TOP' },
  //   { name: 'Trinidad & Tobago Dollar', value: 'TTD' },
  //   { name: 'Tunisian Dinar', value: 'TND' },
  //   { name: 'Turkish Lira', value: 'TRY' },
  //   { name: 'Turkmenistani Manat', value: 'TMT' },
  //   { name: 'Ugandan Shilling', value: 'UGX' },
  //   { name: 'Ukrainian Hryvnia', value: 'UAH' },
  //   { name: 'United Arab Emirates Dirham', value: 'AED' },
  //   { name: 'Uruguayan Peso', value: 'UYU' },
  { name: 'us_dollar', value: 'USD', sign: '$' },
  //   { name: 'Uzbekistan Som', value: 'UZS' },
  //   { name: 'Vanuatu Vatu', value: 'VUV' },
  //   { name: 'Venezuelan BolÃvar', value: 'VEF' },
  //   { name: 'Vietnamese Dong', value: 'VND' },
  //   { name: 'Yemeni Rial', value: 'YER' },
  //   { name: 'Zambian Kwacha', value: 'ZMK' },
  //   { name: 'Zimbabwean dollar', value: 'ZWL' },
];
